version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1.401-sdk
    steps:
      - checkout
      - run:
          name: Install Cake
          command: |
            dotnet tool install -g Cake.Tool
            export PATH="$PATH:/root/.dotnet/tools"
      - run:
          name: Build
          command: dotnet cake build.cake
