version: 2
jobs:
  build:
    docker:
      - image: adamhathcock/cake-build:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build
          command: ./build.sh
      - run:
          name: Make Docker Container
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t conduit:latest .
            fi
      