name: Build and Test CaseFunnel

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: dotnet run -p build/build.csproj
